name: Run Tests

on:
  push:
    branches:
      - main  # 이 부분을 테스트를 실행할 브랜치 이름으로 설정합니다

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Python 설정
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' 

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 필요한 패키지가 requirements.txt에 나열되어 있어야 합니다

      - name: 테스트 실행
        run: |
          pytest
